### PR TITLE
Update ad-nap.png

### LINKED ISSUE #31: Shafik's image reported to have loading issues
ad-nap.png needs to be changed as pushing the same image still causes loading issues in the AboutUs.md

### PR DESCRIPTION
**Pull request by AD-NAP**
Previous photo has loading issue mentioned.

Add a new photo to resolve said issue.

This should resolve #31.

### CODE REVIEW

**Comment by AD-NAP** [comment]
bug still persists... 😞

**Comment by AD-NAP** [comment]
Renamed file to ad-nap.png as per github username.
Bug found: naming the file with hyphen causes loading issues in github. 
Unable to find a solution other than removing the hyphen. Will rectify with TA regarding this.

**Comment by j4ck990** [comment]
I'll hold off on merging #32 first

**Review by Vishwanth2210 — APPROVED** [review]
Good job finding the bug and fixing the issue. The image is visible now.

**Pull request merged**
